import{a as d,S as h,i as l}from"./assets/vendor-f736e62a.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const p of o.addedNodes)p.tagName==="LINK"&&p.rel==="modulepreload"&&s(p)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();async function u(a,t){const n="43757343-ba5778b701f459784bea5ede7";d.defaults.baseURL="https://pixabay.com/api/";const s=`?key=${n}&q=${a}&image_type=photo&orientation=horizontal&safesearch=true&page=${t}&per_page=15`;try{const{data:e}=await d.get(s);return e}catch(e){console.log(e)}}function f(a,t){const n=a.reduce((s,e)=>s+=`<div class="gallery">
          <a href="${e.largeImageURL}"><img src="${e.webformatURL}" alt="${e.tags}"  width="360"/></a>
          <div class="info">
              <p>Likes <span></span>${e.likes}</span></p>
              <p>Views <span></span>${e.views}</span></p>
              <p>Comments <span></span>${e.comments}</span></p>
              <p>Downloads <span></span>${e.downloads}</span></p>
          </div>
              </div>`,"");t.insertAdjacentHTML("beforeend",n)}const r={formEL:document.querySelector("#form"),inputEL:document.querySelector("#image-input"),galleryEL:document.querySelector("#gallery"),loadMoreBtn:document.querySelector(".load-more"),loaderEl:document.querySelector("#loader-js")};let c="",i=1,g=new h("#gallery a",{captionsData:"alt",captionDelay:250});function m(a){if(a.preventDefault(),r.loadMoreBtn.classList.remove("is-visible"),i=1,r.galleryEL.innerHTML='<span class="loader"></span>',c=r.inputEL.value.trim(),c==="")return l.show({title:"⨻",titleSize:"20px",message:"Introduction field please enter the value to search",color:"white",backgroundColor:"red",position:"topRight"});u(c,i).then(t=>{if(t.totalHits===0)return l.show({title:"⨻",titleSize:"20px",message:"Sorry, there are no images matching your search query. Please try again!",color:"white",backgroundColor:"red",position:"topRight"});r.galleryEL.innerHTML="",f(t.hits,r.galleryEL),g.refresh(),t.totalHits>15&&r.loadMoreBtn.classList.add("is-visible")}).catch(t=>{l.show({title:"⨻",titleSize:"20px",message:"Something went wrong. Please try again",color:"white",backgroundColor:"red",position:"topRight"})}),r.formEL.reset()}function y(a){r.loaderEl.innerHTML='<span class="loader"></span>',i+=1,u(c,i).then(t=>{r.loaderEl.innerHTML="",f(t.hits,r.galleryEL);const n=document.querySelector(".gallery");g.refresh();const s=n.getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"}),Math.ceil(t.totalHits/15)===i&&(r.loadMoreBtn.classList.remove("is-visible"),l.show({title:"⨻",titleSize:"20px",message:"We're sorry, but you've reached the end of search results.",color:"white",backgroundColor:"navy-blue",position:"topRight"}))})}r.formEL.addEventListener("submit",m);r.loadMoreBtn.addEventListener("click",y);
//# sourceMappingURL=commonHelpers.js.map
