import{a as p,S as g,i as u}from"./assets/vendor-f736e62a.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();async function d(a,t){const i="43757343-ba5778b701f459784bea5ede7";p.defaults.baseURL="https://pixabay.com/api/";const s=`?key=${i}&q=${a}&image_type=photo&orientation=horizontal&safesearch=true&page=${t}&per_page=15`,{data:e}=await p.get(s);return e}function f(a,t){const i=a.reduce((s,e)=>s+=`<div class="gallery">
          <a href="${e.largeImageURL}"><img src="${e.webformatURL}" alt="${e.tags}"  width="360"/></a>
          <div class="info">
              <p>Likes <span></span>${e.likes}</span></p>
              <p>Views <span></span>${e.views}</span></p>
              <p>Comments <span></span>${e.comments}</span></p>
              <p>Downloads <span></span>${e.downloads}</span></p>
          </div>
              </div>`,"");t.insertAdjacentHTML("beforeend",i)}const o={formEL:document.querySelector("#form"),inputEL:document.querySelector("#image-input"),galleryEL:document.querySelector("#gallery"),loadMoreBtn:document.querySelector(".load-more")};let l="",n=1,h=new g("#gallery a",{captionsData:"alt",captionDelay:250});function m(a){if(a.preventDefault(),o.loadMoreBtn.classList.remove("is-visible"),n=1,o.galleryEL.innerHTML='<span class="loader"></span>',l=o.inputEL.value.trim(),l==="")return u.show({title:"⨻",titleSize:"20px",message:"Introduction field please enter the value to search",color:"white",backgroundColor:"red",position:"topRight"});d(l,n).then(t=>{if(t.totalHits===0)return u.show({title:"⨻",titleSize:"20px",message:"Sorry, there are no images matching your search query. Please try again!",color:"white",backgroundColor:"red",position:"topRight"});o.galleryEL.innerHTML="",h.refresh(),f(t.hits,o.galleryEL),t.totalHits>15&&o.loadMoreBtn.classList.add("is-visible")}),o.formEL.reset()}function y(a){n+=1,d(l,n).then(t=>{f(t.hits,o.galleryEL);const i=document.querySelector(".gallery");h.refresh();const s=i.getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"}),Math.ceil(t.totalHits/15)===n&&(o.loadMoreBtn.classList.remove("is-visible"),u.show({title:"⨻",titleSize:"20px",message:"We're sorry, but you've reached the end of search results.",color:"white",backgroundColor:"navy-blue",position:"topRight"}))})}o.formEL.addEventListener("submit",m);o.loadMoreBtn.addEventListener("click",y);
//# sourceMappingURL=commonHelpers.js.map
